openapi: 3.0.0
info:
  title: Bank Offers API
  description: API to retrieve offers for customers and status offer.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /customers/{customerId}/offers:
    get:
      summary: Get offers for a specific customer
      description: Retrieve all offers for a customer identified by their ID.
      parameters:
        - name: customerId
          in: path
          required: true
          description: The ID of the customer to retrieve offers for.
          schema:
            type: string
      responses:
        '200':
          description: A list of offers for the specified customer.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OfferStatus'
        '404':
          description: No offers found for the specified customer.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'

components:
  schemas:
    Offer:
      type: object
      properties:
        id:
          type: string
          example: "offer1"
        customerId:
          type: string
          example: "customer1"
        creationDate:
          type: string
          format: date-time
          example: "2023-01-01T00:00:00Z"
        rejectionDate:
          type: string
          format: date-time
          example: "2023-01-10T00:00:00Z"
    OfferStatus:
      type: object
      properties:
        offer:
          $ref: '#/components/schemas/Offer'
        status:
          type: string
          example: "IN PROGRESS"
    ErrorDetails:
      type: object
      properties:
        message:
          type: string
          example: "Resource not found"
        details:
          type: string
          example: "No offers found for customer id: customer1"
